### ISSUE TITLE
Knuckles: "Gentleman" window lasts forever if no action is taken

### ISSUE THREAD

**Issue by B94** [TheOriginalSINe/Project-M-CC#272]
After pressing Jab twice, there is an indefinite window to do the finishing jab if no action has been taken. The window is removed if any other button is pressed.

**Comment by Kippy232** [comment]
Could you elaborate on the first part, Knuckles' jab? I'm not seeing the problem here.

So make Knuckles' yellow spring have a lower spring height? That part of this issue has been covered by Issue https://github.com/TheOriginalSINe/Project-M-CC/issues/158.

**Comment by B94** [comment]
Okay. The problem is that no matter how long you wait, the third jab will come out if you do nothing after pressing A after going to jab 2. The window to execute the third jab doesn't have a proper closing point. Imagine Fox's jab lock combo on Smash 4 (Jabs 1 and 2 repeatedly) being fixed by forcing the rapid kicks no matter how long you wait to press A after the second jab, even when you return to neutral (and do nothing) for 30 seconds. If you move, jump, shield, do a special, etc., you can press A to do the first jab again.
I didn't notice that submission about his spring when I looked over the posts before making this. Thanks.

**Comment by ArtfulHobbes** [comment]
I see what you mean. I'll look into it and see if I can fix it.

**Comment by Kosyne** [comment]
Can confirm this still happens on the new Knuckles.

As for looking into it... What's going to be the deciding factor on how long the window lasts, @ArtfulHobbes? FWIW, I often find myself putting a bit of delay on the last hit when playing.

**Comment by bb010g** [comment]
I'd say leave it for now and see if we need to fix it for balance in the future. Jab 3 is one of his better ground normals, and the setup of jabs 1 & 2 and no movement make it so you can't just throw it out.

What windows do other characters have for switching back to jab 1?

**Comment by Kosyne** [comment]
I don't know the frames, but Link's at least is fairly small. I too like how it is now, just not really sure if that's intentional.

**Comment by bb010g** [comment]
Who's working/planning on working on this?

**Comment by vinegar97** [comment]
@rage17 has fixed this along some other issues from #351, they'll be committed soon enough
